<?php

namespace Database\Seeders\knowledge;

class BotKnowledgeFaqAgamaSosialUmum
{
    public function getFaqKeagamaan(): array
    {
        return [
            [
                'kunci' => 'faq-ag-001',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jadwal Shalat Berjamaah di Meunasah',
                'kata_kunci' => ['shalat', 'jadwal', 'meunasah', 'berjamaah', 'waktu shalat'],
                'jawaban_atau_konten' => 'Shalat berjamaah dilaksanakan di Meunasah Desa Udeung setiap waktu. Jadwal shalat lima waktu: Shubuh 04.45 WIB, Dzuhur 12.15 WIB, Ashar 15.30 WIB, Maghrib 18.15 WIB, Isya 19.30 WIB. Untuk shalat Jumat, dilaksanakan pukul 12.00 WIB di Meunasah Utama.',
            ],
            [
                'kunci' => 'faq-ag-002',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Shalat Jumat di Meunasah Desa Udeung',
                'kata_kunci' => ['jumat', 'shalat jumat', 'meunasah', 'khatib', 'imam'],
                'jawaban_atau_konten' => 'Shalat Jumat dilaksanakan di Meunasah Utama Desa Udeung setiap hari Jumat pukul 12.00 WIB. Khatib dan imam shalat ditunjuk secara bergilir oleh pengurus meunasah. Jemaah diharapkan hadir minimal 15 menit sebelum waktu shalat.',
            ],
            [
                'kunci' => 'faq-ag-003',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jadwal Pengajian di Desa Udeung',
                'kata_kunci' => ['pengajian', 'jadwal', 'mengaji', 'belajar'],
                'jawaban_atau_konten' => 'Pengajian rutin di Desa Udeung diadakan setiap hari Selasa dan Kamis malam pukul 20.00 WIB di Meunasah. Untuk pengajian ibu-ibu diadakan setiap hari Rabu pagi pukul 09.00 WIB. Pengajian anak-anak TPA diadakan setiap hari setelah Shubuh.',
            ],
            [
                'kunci' => 'faq-ag-004',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Majelis Taklim Desa Udeung',
                'kata_kunci' => ['majelis taklim', 'tausiyah', 'ustadz', 'ceramah'],
                'jawaban_atau_konten' => 'Majelis Taklim Desa Udeung beranggotakan ibu-ibu yang aktif. Pertemuan rutin diadakan setiap hari Rabu pukul 09.00 WIB di Meunasah. Agenda meliputi tafsir Al-Quran, fiqih, dan tausiyah. Ustadz pembimbing saat ini dari Dayah Darul Akhbar.',
            ],
            [
                'kunci' => 'faq-ag-005',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Tausiyah dan Ceramah Agama',
                'kata_kunci' => ['tausiyah', 'ceramah', 'ustadz', 'kajian'],
                'jawaban_atau_konten' => 'Tausiyah agama di Desa Udeung diadakan secara berkala, biasanya satu bulan sekali pada malam Jumat. Tema tausiyah berputar antara akhlak, fiqih, dan sejarah Islam. Untuk informasi jadwal terkini, hubungi Ketua Takmir Meunasah.',
            ],
            [
                'kunci' => 'faq-ag-006',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara Menyalurkan Zakat di Desa Udeung',
                'kata_kunci' => ['zakat', 'menyalurkan', 'amil', 'zakat fitrah'],
                'jawaban_atau_konten' => 'Zakat dapat disalurkan melalui Amil Zakat Desa Udeung yang ditunjuk oleh Kepala Desa. Penerimaan zakat fitrah dan zakat mal dilakukan menjelang Hari Raya. Bisa juga disalurkan langsung ke mustahik (penerima zakat) yang sudah terdata. Hubungi Kepala Desa atau Ketua Takmir untuk informasi lebih lanjut.',
            ],
            [
                'kunci' => 'faq-ag-007',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Zakat Fitrah Desa Udeung',
                'kata_kunci' => ['zakat fitrah', 'beras', 'harga', 'bayar zakat'],
                'jawaban_atau_konten' => 'Zakat fitrah di Desa Udeung ditentukan setiap tahun menjelang Idul Fitri. Besaran zakat fitrah mengikuti ketetapan dari Dinas Syariat Islam Aceh. Biasanya setara dengan 2,5 kg beras per jiwa. Pembayaran zakat fitrah bisa dilakukan di Meunasah atau langsung ke rumah mustahik.',
            ],
            [
                'kunci' => 'faq-ag-008',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Zakat Mal dan Fitnah',
                'kata_kunci' => ['zakat mal', 'harta', 'penghasilan', 'nisab'],
                'jawaban_atau_konten' => 'Zakat mal adalah zakat atas harta yang mencapai nisab dan telah mencapai haul (satu tahun). Di Desa Udeung, zakat mal dapat disalurkan melalui Baitul Mal Desa atau langsung ke mustahik yang berhak. Untuk konsultasi perhitungan zakat mal, silakan hubungi pengurus meunasah.',
            ],
            [
                'kunci' => 'faq-ag-009',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara Berdonasi atau Berinfaq di Desa Udeung',
                'kata_kunci' => ['infaq', 'sedekah', 'donasi', 'berdonasi'],
                'jawaban_atau_konten' => 'Infaq dan sedekah dapat disalurkan melalui kotak infaq yang tersedia di Meunasah Desa Udeung. Selain itu, dapat juga melalui rekening Baitul Mal Desa atau langsung ke pengurus. Donasi digunakan untuk kegiatan keagamaan, pembangunan meunasah, dan bantuan fakir miskin.',
            ],
            [
                'kunci' => 'faq-ag-010',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Sedekah Jumat Desa Udeung',
                'kata_kunci' => ['sedekah', 'jumat', 'berkah', 'donasi'],
                'jawaban_atau_konten' => 'Program Sedekah Jumat di Desa Udeung dilakukan setiap hari Jumat setelah shalat Jumat. Dana yang terkumpul disalurkan kepada fakir miskin, anak yatim, dan kebutuhan meunasah. Masyarakat dapat menyalurkan sedekah melalui kotak infaq di meunasah.',
            ],
            [
                'kunci' => 'faq-ag-011',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jadwal TPA di Desa Udeung',
                'kata_kunci' => ['TPA', 'anak', 'mengaji', 'jadwal', 'taman Pendidikan Al-Quran'],
                'jawaban_atau_konten' => 'Taman Pendidikan Al-Qur\'an (TPA) di Desa Udeung diadakan setiap hari setelah Shubuh pukul 05.00-06.30 WIB dan sore hari pukul 16.00-17.30 WIB. Lokasi belajar di Meunasah. TPA menerima anak usia 4-12 tahun.',
            ],
            [
                'kunci' => 'faq-ag-012',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pendaftaran TPA Desa Udeung',
                'kata_kunci' => ['pendaftaran', 'TPA', 'daftar', 'anak'],
                'jawaban_atau_konten' => 'Pendaftaran TPA Desa Udeung dapat dilakukan langsung ke Meunasah atau menghubungi Ustazah/ustadz pembimbing. Pendaftaran gratis, hanya dibutuhkan fotokopi akte kelahiran dan surat keterangan sehat. Kuota TPA maksimal 40 anak per kelompok.',
            ],
            [
                'kunci' => 'faq-ag-013',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kurikulum TPA Desa Udeung',
                'kata_kunci' => ['kurikulum', 'TPA', 'belajar', 'baca tulis Al-Qur\'an'],
                'jawaban_atau_konten' => 'Kurikulum TPA Desa Udeung mengikuti standar Kementerian Agama. Materi meliputi: baca tulis Al-Qur\'an, hafalan surat-surat pendek, doa harian, dan adab. Sistem pembelajaran bertahap dari Iqra\' hingga Juz 30.',
            ],
            [
                'kunci' => 'faq-ag-014',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Tugas Marbot Meunasah',
                'kata_kunci' => ['marbot', 'tugas', 'meunasah', 'merawat'],
                'jawaban_atau_konten' => 'Marbot Meunasah bertanggung jawab atas kebersihan dan pemeliharaan Meunasah Desa Udeung. Tugas meliputi: membersihkan lantai, mengatur AC, membuka-menutup pintu meunasah, memastikan perlengkapan shalat lengkap, dan menjaga keamanan saat tidak ada kegiatan.',
            ],
            [
                'kunci' => 'faq-ag-015',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara Mendaftar Menjadi Marbot',
                'kata_kunci' => ['marbot', 'mendaftar', 'volunteer', 'meunasah'],
                'jawaban_atau_konten' => 'Pendaftaran marbot Meunasah dapat dilakukan dengan menghubungi Kepala Desa atau Ketua Takmir Desa Udeung. Marbot mendapat insentif bulanan dari dana desa. Syarat: muslim, sehat jasmani, berdomisili di Desa Udeung, dan bersedia bertugas sesuai jadwal.',
            ],
            [
                'kunci' => 'faq-ag-016',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Qanun Aceh tentang Perkawinan',
                'kata_kunci' => ['qanun', 'Aceh', 'perkawinan', 'nikah', 'hukum'],
                'jawaban_atau_konten' => 'Qanun Aceh Nomor 9 Tahun 2008 tentang Hukum Keluarga mengatur perkawinan di Aceh. Beberapa ketentuan penting: usia minimal nikah 19 tahun, wajib adanya wali, dan perkawinan harus dicatat di Kantor Urusan Agama. Untuk konsultasi hukum syariat, silakan hubungi Kantor Kepala Desa.',
            ],
            [
                'kunci' => 'faq-ag-017',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Qanun Aceh tentang Minuman Keras',
                'kata_kunci' => ['qanun', 'Aceh', 'khamr', 'minuman keras', 'larangan'],
                'jawaban_atau_konten' => 'Qanun Aceh tentang Jinayat mengatur larangan produksi, penjualan, dan konsumsi minuman keras (khamr) di Aceh. Pelanggaran dapat dikenakan sanksi sesuai hukum syariat. Masyarakat diimbau untuk melaporkan jika menemukan aktivitas penjualan minuman keras di lingkungan desa.',
            ],
            [
                'kunci' => 'faq-ag-018',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Qanun Aceh tentang Judi',
                'kata_kunci' => ['qanun', 'Aceh', 'judi', 'perjudian', 'larangan'],
                'jawaban_atau_konten' => 'Perjudian dilarang keras di Aceh berdasarkan Qanun Jinayat. Bentuk perjudian apapun termasuk togel dan judi online tidak diperbolehkan. Pelanggar dapat dikenakan hukuman cambuk dan denda. Laporkan aktivitas mencurigakan kepada Kepala Desa atau pihak berwajib.',
            ],
            [
                'kunci' => 'faq-ag-019',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kegiatan Bulan Ramadhan di Desa Udeung',
                'kata_kunci' => ['ramadhan', 'puasa', 'kegiatan', 'bulan puasa'],
                'jawaban_atau_konten' => 'Selama bulan Ramadhan, Desa Udeung menyelenggarakan berbagai kegiatan: shalat Tarawih berjamaah, tadarus Al-Qur\'an, buka puasa bersama, shalat Shubuh berjamaah, dan ceramah malam. Jadwal lengkap diumumkan di Meunasah dan media sosial desa.',
            ],
            [
                'kunci' => 'faq-ag-020',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Shalat Tarawih di Desa Udeung',
                'kata_kunci' => ['tarawih', 'ramadhan', 'shalat malam', 'meunasah'],
                'jawaban_atau_konten' => 'Shalat Tarawih dilaksanakan di Meunasah Utama Desa Udeung setiap malam selama Ramadhan. Dimulai pukul 20.00 WIB setelah shalat Isya. Tarawih 20 rakaat dilaksanakan berjamaah dengan imam yang ditunjuk. Jemaah diharapkan hadir tepat waktu.',
            ],
            [
                'kunci' => 'faq-ag-021',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Buka Puasa Bersama Desa Udeung',
                'kata_kunci' => ['buka puasa', 'bersama', 'ramadhan', 'ma\'idah'],
                'jawaban_atau_konten' => 'Buka puasa bersama di Desa Udeung diadakan setiap malam di Meunasah. Diselenggarakan secara bergilir oleh masing-masing dusun. Dana buka puasa bersama berasal dari infaq masyarakat dan donatur. Masyarakat diharapkan hadir untuk mempererat silaturahmi.',
            ],
            [
                'kunci' => 'faq-ag-022',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Takbiran Malam Idul Fitri',
                'kata_kunci' => ['takbiran', 'idul fitri', 'malam', 'takbir'],
                'jawaban_atau_konten' => 'Takbiran malam Idul Fitri di Desa Udeung dilaksanakan di Meunasah Utama pukul 20.00 WIB. Acara diisi dengan takbir, tahlil, doa, dan ceramah singkat. Masyarakat berjalan keliling desa sambil bertakbir. Sebelum takbiran, dilaksanakan shalat Maghrib berjamaah.',
            ],
            [
                'kunci' => 'faq-ag-023',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Zakat Fitri menjelang Idul Fitri',
                'kata_kunci' => ['zakat fitri', 'idul fitri', 'zakat', 'sebelum shalat'],
                'jawaban_atau_konten' => 'Zakat fitri wajib dibayarkan sebelum shalat Idul Fitri. Di Desa Udeung, pembayaran zakat fitri dilakukan di Meunasah atau melalui amil yang ditunjuk. Besaran zakat fitrah mengikuti ketetapan resmi dari pemerintah. Pastikan seluruh anggota keluarga tercatat untuk pembayaran zakat.',
            ],
            [
                'kunci' => 'faq-ag-024',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Halal Bihalal di Desa Udeung',
                'kata_kunci' => ['halal bi halal', 'idul fitri', 'silaturahmi', 'mohon maaf'],
                'jawaban_atau_konten' => 'Halal bi halal di Desa Udeung diadakan sehari setelah Idul Fitri di Meunasah Utama pukul 10.00 WIB. Acara ini menjadi ajang silaturahmi dan saling memaafkan antar warga. Seluruh masyarakat diundang untuk hadir. Disajikan hidangan khas Lebaran.',
            ],
            [
                'kunci' => 'faq-ag-025',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Persiapan Idul Adha di Desa Udeung',
                'kata_kunci' => ['idul adha', 'qurban', 'kurban', 'haji'],
                'jawaban_atau_konten' => 'Persiapan Idul Adha di Desa Udeung meliputi: pengumpulan dana qurban, pendaftaran peserta qurban, dan pemilihan hewan. Pendaftaran qurban dibuka satu bulan sebelum Idul Adha. Hewan qurban disembelih di tempat yang telah disediakan di Meunasah.',
            ],
            [
                'kunci' => 'faq-ag-026',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara Qurban di Desa Udeung',
                'kata_kunci' => ['qurban', 'kurban', 'sapi', 'kambing', 'daftar'],
                'jawaban_atau_konten' => 'Untuk berqurban di Desa Udeung, masyarakat dapat mendaftarkan diri atau keluarga di Meunasah atau menghubungi panitia qurban. Hewan qurban berupa sapi atau kambing. Daging qurban dibagikan kepada yang berhak menerima di Desa Udeung.',
            ],
            [
                'kunci' => 'faq-ag-027',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pembagian Daging Qurban',
                'kata_kunci' => ['daging', 'qurban', 'kurban', 'pembagian', 'mustahik'],
                'jawaban_atau_konten' => 'Pembagian daging qurban di Desa Udeung dilakukan setelah penyembelihan pada hari Idul Adha. Daging dibagikan secara merata kepada seluruh warga yang telah terdaftar. Untuk warga yang tidak mampu, distribusi daging dilakukan door to door oleh panitia.',
            ],
            [
                'kunci' => 'faq-ag-028',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Shalat Idul Fitri dan Idul Adha',
                'kata_kunci' => ['shalat id', 'idul fitri', 'idul adha', 'lapangan'],
                'jawaban_atau_konten' => 'Shalat Idul Fitri dan Idul Adha dilaksanakan di Meunasah Utama atau lapangan terbuka Desa Udeung pukul 07.00 WIB. Setelah shalat, diadakan khutbah Id. Masyarakat diharapkan hadir lebih awal dan memakai pakaian terbaik.',
            ],
            [
                'kunci' => 'faq-ag-029',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Dana Baitul Mal Desa Udeung',
                'kata_kunci' => ['baitul mal', 'dana', 'zakat', 'infaq', 'keuangan'],
                'jawaban_atau_konten' => 'Baitul Mal Desa Udeung mengelola dana zakat, infaq, dan sedekah dari masyarakat. Dana digunakan untuk: membantu fakir miskin, beasiswa pendidikan, bantuan kegiatan keagamaan, dan pembangunan fasilitas ibadah. Laporan keuangan Baitul Mal diajukan setiap triwulan.',
            ],
            [
                'kunci' => 'faq-ag-030',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Hukum Syariat di Aceh',
                'kata_kunci' => ['hukum syariat', 'qanun', 'hukum islam', 'Aceh'],
                'jawaban_atau_konten' => 'Aceh memiliki otonomi khusus dalam menerapkan hukum syariat Islam berdasarkan Qanun Aceh. Hukum syariat mengatur aspek kehidupan seperti perdata, jinayat (pidana), dan muamalah. Informasi lebih lanjut dapat menghubungi Kantor Dinas Syariat Islam atau Kepala Desa Desa.',
            ],
        ];
    }

    public function getFaqSosial(): array
    {
        return [
            [
                'kunci' => 'faq-sos-001',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jadwal Gotong Royong di Desa Udeung',
                'kata_kunci' => ['gotong royong', 'jadwal', 'kerja bakti', 'membersihkan'],
                'jawaban_atau_konten' => 'Gotong royong di Desa Udeung dilaksanakan setiap hari Minggu pagi pukul 07.00 WIB. Kegiatan meliputi pembersihan jalan, parit, dan fasilitas umum. Warga diwajibkan berpartisipasi sesuai daftar yang disusun oleh Kepala Desa per dusun.',
            ],
            [
                'kunci' => 'faq-sos-002',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Lokasi Gotong Royong',
                'kata_kunci' => ['gotong royong', 'lokasi', 'tempat', 'berkumpul'],
                'jawaban_atau_konten' => 'Titik kumpul gotong royong di Desa Udeung berada di depan Meunasah Utama. Setiap kegiatan gotong royong, lokasi akan diumumkan melalui pengeras suara meunasah atau group WhatsApp desa. Persiapkan peralatan sendiri seperti cangkul, sapu, dan karung.',
            ],
            [
                'kunci' => 'faq-sos-003',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kewajiban Warga dalam Gotong Royong',
                'kata_kunci' => ['gotong royong', 'kewajiban', 'warga', 'partisipasi'],
                'jawaban_atau_konten' => 'Seluruh warga Desa Udeung yang sudah menikah wajib berpartisipasi dalam gotong royong. Bagi yang berhalangan hadir, dapat menggantikan dengan uang sebesar Rp 20.000 atau menitipkan orang lain. Kewajiban ini merupakan bagian dari gotong royong wajib berdasarkan keputusan desa.',
            ],
            [
                'kunci' => 'faq-sos-004',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Siskamling di Desa Udeung',
                'kata_kunci' => ['siskamling', 'keamanan', 'ronda', 'malam'],
                'jawaban_atau_konten' => 'Sistem Keamanan Lingkungan (Siskamling) di Desa Udeung beroperasi setiap malam pukul 21.00-06.00 WIB. Pos ronda terletak di setiap dusun. Jadwal jaga disusun per bulan dan diumumkan di masing-masing dusun. Setiap KK wajib berpartisipasi minimal satu malam per bulan.',
            ],
            [
                'kunci' => 'faq-sos-005',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pos Kamling Desa Udeung',
                'kata_kunci' => ['pos kamling', 'keamanan', 'ronda', 'pos'],
                'jawaban_atau_konten' => 'Pos Kamling di Desa Udeung terdapat di 4 titik, masing-masing di setiap dusun. Pos dilengkapi dengan tempat tidur, selimut, dan alat komunikasi. Untuk laporan keamanan, hubungi Kepala Desa atau anggota Polsek terdekat.',
            ],
            [
                'kunci' => 'faq-sos-006',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jadwal Ronda Malam',
                'kata_kunci' => ['ronda', 'jadwal', 'malam', 'keamanan'],
                'jawaban_atau_konten' => 'Jadwal ronda malam di Desa Udeung disusun per dusun oleh Kepala Desa Dusun. Setiap KK mendapat giliran minimal satu malam per bulan. Ronda dimulai pukul 21.00 WIB hingga Shubuh. Petugas ronda wajib membawa lampu senter dan alat komunikasi.',
            ],
            [
                'kunci' => 'faq-sos-007',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Karang Taruna Desa Udeung',
                'kata_kunci' => ['karang taruna', 'organisasi', 'pemuda', 'kegiatan'],
                'jawaban_atau_konten' => 'Karang Taruna Desa Udeung adalah organisasi pemuda yang aktif dalam kegiatan sosial kemasyarakatan. Kegiatan rutin meliputi: bakti sosial, turnamen olahraga, pengajian pemuda, dan kegiatan budaya. Keanggotaan terbuka untuk pemuda usia 16-30 tahun.',
            ],
            [
                'kunci' => 'faq-sos-008',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'PKK Desa Udeung',
                'kata_kunci' => ['PKK', 'organisasi', 'ibu', 'perempuan', 'pemberdayaan'],
                'jawaban_atau_konten' => 'Pemberdayaan Kesejahteraan Keluarga (PKK) Desa Udeung aktif dalam pemberdayaan perempuan dan keluarga. Kegiatan meliputi: posyandu, pengajian ibu-ibu, pelatihan keterampilan, dan program pengentasan kemiskinan. PKK bernaung di bawah Kantor Kepala Desa.',
            ],
            [
                'kunci' => 'faq-sos-009',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kelompok Tani Desa Udeung',
                'kata_kunci' => ['kelompok tani', 'pertanian', 'sawah', 'petani'],
                'jawaban_atau_konten' => 'Kelompok Tani Desa Udeung beranggotakan para petani yang menggarap lahan pertanian di wilayah desa. Kegiatan meliputi: bimbingan teknis pertanian, pengadaan pupuk dan benih, pemasaran hasil panen, dan kerja sama dengan Dinas Pertanian Kabupaten.',
            ],
            [
                'kunci' => 'faq-sos-010',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara Melapor Bencana Alam',
                'kata_kunci' => ['bencana', 'melapor', 'darurat', 'banjir', 'gempa'],
                'jawaban_atau_konten' => 'Untuk melapor bencana alam di Desa Udeung, hubungi Kepala Desa di nomor yang tertera di papan informasi desa, atau hubungi nomor darurat 112. Laporkan juga ke Babinsa atau Bhabinkamtibmas. Untuk bencana besar, hubungi BPBD Kabupaten.',
            ],
            [
                'kunci' => 'faq-sos-011',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Banjir di Desa Udeung',
                'kata_kunci' => ['banjir', 'bencana', 'air', 'hujan'],
                'jawaban_atau_konten' => 'Desa Udeung kadang mengalami banjir saat musim hujan dengan curah hujan tinggi. Titik rawan banjir di area dekat sungai. Jika terjadi banjir, segera hubungi Kepala Desa dan siapkan dokumen penting di tempat aman. Evakuasi ke meunasah jika diperlukan.',
            ],
            [
                'kunci' => 'faq-sos-012',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Longsor di Desa Udeung',
                'kata_kunci' => ['longsor', 'bencana', 'tanah', 'perbukitan'],
                'jawaban_atau_konten' => 'Potensi longsor di Desa Udeung terdapat di area perbukitan. Jika hujan deras berkepanjangan, waspadai tanda-tanda longsor seperti retakan tanah dan air keruh. Segera hubungi Kepala Desa dan evakuasi jika diperlukan. Hindari area lereng saat hujan.',
            ],
            [
                'kunci' => 'faq-sos-013',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Gempa Bumi dan Persiapan',
                'kata_kunci' => ['gempa', 'bencana', 'gempa bumi', 'persiapan'],
                'jawaban_atau_konten' => 'Desa Udeung berada di wilayah rawan gempa. Persiapan menghadapi gempa: sediakan tas darurat, pahami jalur evakuasi, dan ikuti pelatihan simulasi gempa. Titik kumpul darurat di lapangan desa dan meunasah. Jika gempa terjadi, lindungi kepala dan mencari tempat aman.',
            ],
            [
                'kunci' => 'faq-sos-014',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Program Bantuan Lansia',
                'kata_kunci' => ['lansia', 'bantuan', 'perawatan', 'orang tua'],
                'jawaban_atau_konten' => 'Desa Udeung memiliki program bantuan untuk lansia melalui posyandu lansia. Bantuan meliputi: pemeriksaan kesehatan rutin, suplemen makanan, dan kunjungan rumah. Lansia yang membutuhkan perawatan intensif dapat menghubungi Kepala Desa untuk didaftarkan.',
            ],
            [
                'kunci' => 'faq-sos-015',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Perawatan Lansia di Desa Udeung',
                'kata_kunci' => ['lansia', 'perawatan', 'kesehatan', 'posyandu'],
                'jawaban_atau_konten' => 'Perawatan lansia di Desa Udeung dilakukan melalui posyandu lansia yang beroperasi setiap bulan. Petugas kesehatan dari Puskesmas melakukan pemeriksaan rutin. Keluarga diimbau untuk memperhatikan kesehatan lansia di rumah dan membawa ke posyandu secara berkala.',
            ],
            [
                'kunci' => 'faq-sos-016',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan untuk Yatim Piatu',
                'kata_kunci' => ['yatim piatu', 'bantuan', 'anak', 'yayasan'],
                'jawaban_atau_konten' => 'Desa Udeung memiliki program bantuan untuk anak yatim piatu melalui Baitul Mal Desa. Bantuan meliputi: biaya pendidikan, pakaian, dan kebutuhan sehari-hari. Untuk mendaftar, datang ke Kepala Desa dengan membawa surat keterangan dari keluarga atau pengurus mesjid.',
            ],
            [
                'kunci' => 'faq-sos-017',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Yayasan Yatim Piatu di Aceh',
                'kata_kunci' => ['yayasan', 'yatim piatu', 'panti', 'bantuan'],
                'jawaban_atau_konten' => 'Di Aceh terdapat beberapa yayasan yang menampung anak yatim piatu seperti Rumah Yatim dan Panti Asuhan Baitul Mustaqim. Untuk donasi atau menitipkan anak yatim piatu, silakan menghubungi yayasan terdekat. Informasi lebih lanjut dapat ditanyakan di Kepala Desa.',
            ],
            [
                'kunci' => 'faq-sos-018',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Hak dan Bantuan Disabilitas',
                'kata_kunci' => ['disabilitas', 'hak', 'bantuan', 'difabel'],
                'jawaban_atau_konten' => 'Penyandang disabilitas di Desa Udeung berhak mendapatkan: akses pendidikan, bantuan alat bantu, dan program pemberdayaan. Hubungi Kepala Desa untuk mendaftarkan penyandang disabilitas dalam program bantuan. Pemerintah Kabupaten juga menyediakan bantuan khusus disabilitas.',
            ],
            [
                'kunci' => 'faq-sos-019',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Aksesibilitas untuk Disabilitas',
                'kata_kunci' => ['disabilitas', 'aksesibilitas', 'ramah', 'fasilitas'],
                'jawaban_atau_konten' => 'Desa Udeung terus berupaya meningkatkan aksesibilitas bagi penyandang disabilitas. Saat ini tersedia jalur khusus di beberapa fasilitas umum. Untuk kebutuhan aksesibilitas khusus, silakan sampaikan kepada Kepala Desa untuk ditindaklanjuti.',
            ],
            [
                'kunci' => 'faq-sos-020',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pemberdayaan Perempuan di Desa Udeung',
                'kata_kunci' => ['perempuan', 'pemberdayaan', 'wanita', 'keterampilan'],
                'jawaban_atau_konten' => 'Program pemberdayaan perempuan di Desa Udeung dilaksanakan melalui PKK dan kelompok usaha bersama (KUB). Kegiatan meliputi: pelatihan menjahit, pengolahan makanan, kerajinan tani, dan koperasi simpan pinjam. Pendaftaran melalui pengurus PKK desa.',
            ],
            [
                'kunci' => 'faq-sos-021',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Perlindungan dari Kekerasan terhadap Perempuan',
                'kata_kunci' => ['kekerasan', 'perempuan', 'perlindungan', 'lapor'],
                'jawaban_atau_konten' => 'Jika mengalami atau mengetahui kekerasan terhadap perempuan, segera laporkan ke Kepala Desa, Bhabinkamtibmas, atau Unit Pelayanan Perempuan dan Anak (PPA) di Polres. Bantuan hukum tersedia gratis melalui Pos Bantuan Hukum (Posbakum) Kabupaten.',
            ],
            [
                'kunci' => 'faq-sos-022',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pengelolaan Sampah di Desa Udeung',
                'kata_kunci' => ['sampah', 'organik', 'anorganik', 'tempat sampah'],
                'jawaban_atau_konten' => 'Pengelolaan sampah di Desa Udeung menggunakan sistem pemilahan: sampah organik dan anorganik. TPS3R (Tempat Pengolahan Sampah Reduce Reuse Recycle) beroperasi setiap hari. Masyarakat diimbau memilah sampah dari rumah dan menyerahkan ke TPS3R terdekat.',
            ],
            [
                'kunci' => 'faq-sos-023',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Daur Ulang Sampah',
                'kata_kunci' => ['daur ulang', 'sampah', 'recycle', 'limbah'],
                'jawaban_atau_konten' => 'Desa Udeung memiliki program daur ulang sampah melalui Bank Sampah. Sampah anorganik seperti plastik, kertas, dan kaleng dapat dijual ke Bank Sampah dengan harga bervariasi. Hasil daur ulang diolah menjadi kerajinan tangan bernilai jual.',
            ],
            [
                'kunci' => 'faq-sos-024',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Hemat Air di Desa Udeung',
                'kata_kunci' => ['hemat air', 'air bersih', 'penghematan', 'sumber air'],
                'jawaban_atau_konten' => 'Air bersih di Desa Udeung bersumber dari sumur bor dan PDAM. Masyarakat diimbau untuk menghemat penggunaan air: mematikan keran saat tidak digunakan, memanfaatkan air bekas cuci untuk menyiram tanaman, dan merawat saluran air agar tidak bocor.',
            ],
            [
                'kunci' => 'faq-sos-025',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Adat Istiadat Aceh di Desa Udeung',
                'kata_kunci' => ['adat istiadat', 'budaya', 'Aceh', 'tradisi'],
                'jawaban_atau_konten' => 'Desa Udeung mempertahankan adat istiadat Aceh seperti: Peumulia Jamee (penghormatan tamu), Meugang (penyembelihan hewan saat lebaran), dan Blang (sawah komunal). Upacara adat dilaksanakan saat peristiwa penting dan hari besar.',
            ],
            [
                'kunci' => 'faq-sos-026',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Upacara Adat di Desa Udeung',
                'kata_kunci' => ['upacara adat', 'tradisi', 'adat', 'seremonial'],
                'jawaban_atau_konten' => 'Upacara adat di Desa Udeung dilaksanakan pada momen-momen penting seperti pernikahan, khitanan, dan kematian. Pelaksanaan mengikuti adat istiadat Aceh yang diatur oleh Tim Adat Desa. Untuk informasi jadwal upacara, hubungi Kepala Desa.',
            ],
            [
                'kunci' => 'faq-sos-027',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Tradisi Meugang di Desa Udeung',
                'kata_kunci' => ['meugang', 'tradisi', 'lebaran', 'potong hewan'],
                'jawaban_atau_konten' => 'Meugang adalah tradisi penyembelihan hewan (sapi atau kambing) menjelang Idul Fitri dan Idul Adha di Desa Udeung. Hewan meugang dibeli secara patungan oleh keluarga. Daging dibagikan ke tetangga dan kerabat sebagai bentuk kepedulian sosial.',
            ],
            [
                'kunci' => 'faq-sos-028',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kesenian Tradisional Aceh di Desa Udeung',
                'kata_kunci' => ['kesenian', 'tradisional', 'tari', 'sampan', 'rapa\'i'],
                'jawaban_atau_konten' => 'Desa Udeung memiliki kelompok kesenian tradisional Aceh seperti tari saman, tari ratoh jaroe, dan hadrah. Latihan diadakan di Meunasah setiap minggu. Kelompok kesenian sering tampil saat acara desa dan festival budaya.',
            ],
            [
                'kunci' => 'faq-sos-029',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Gotong Royong Pembangunan Fasilitas',
                'kata_kunci' => ['gotong royong', 'pembangunan', 'fasilitas', 'infrastruktur'],
                'jawaban_atau_konten' => 'Gotong royong pembangunan fasilitas di Desa Udeung dilakukan saat ada proyek pembangunan jalan, jembatan, atau perbaikan meunasah. Kepala Desa mengumumkan jadwal gotong royong khusus melalui pengeras suara atau media sosial desa.',
            ],
            [
                'kunci' => 'faq-sos-030',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Posyandu di Desa Udeung',
                'kata_kunci' => ['posyandu', 'balita', 'ibu hamil', 'kesehatan'],
                'jawaban_atau_konten' => 'Posyandu di Desa Udeung beroperasi setiap tanggal 15 setiap bulan di Meunasah. Pelayanan meliputi: penimbangan balita, imunisasi, pemeriksaan ibu hamil, dan konsultasi gizi. Ibu-ibu dengan balita diharapkan hadir secara rutin.',
            ],
        ];
    }

    public function getFaqUmum(): array
    {
        return [
            [
                'kunci' => 'faq-um-001',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Profil Desa Udeung',
                'kata_kunci' => ['profil', 'desa', 'data umum', 'informasi'],
                'jawaban_atau_konten' => 'Desa Udeung adalah desa yang terletak di Kecamatan Bebesen, Kabupaten Aceh Tengah, Provinsi Aceh. Luas wilayah sekitar 500 hektar dengan jumlah penduduk kurang lebih 1.500 jiwa. Desa ini dipimpin oleh Kepala Desa dan memiliki 4 dusun.',
            ],
            [
                'kunci' => 'faq-um-002',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Visi Misi Desa Udeung',
                'kata_kunci' => ['visi', 'misi', 'desa', 'tujuan'],
                'jawaban_atau_konten' => 'Visi Desa Udeung: Mewujudkan desa yang religius, maju, dan sejahtera. Misi: meningkatkan kegiatan keagamaan, membangun infrastruktur, pemberdayaan masyarakat, dan pelestarian budaya. Rencana pembangunan dituangkan dalam Musrenbang tahunan.',
            ],
            [
                'kunci' => 'faq-um-003',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Sejarah Asal Usul Desa Udeung',
                'kata_kunci' => ['sejarah', 'asal usul', 'berdiri', 'pendiri'],
                'jawaban_atau_konten' => 'Desa Udeung berdiri sekitar abad ke-17. Nama Udeung berasal dari bahasa Aceh yang berarti "batu besar" karena di wilayah desa terdapat batu besar yang menjadi penanda. Desa ini didirikan oleh sekumpulan perantau yang menetap dan membuka lahan pertanian.',
            ],
            [
                'kunci' => 'faq-um-004',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Makna Nama Desa Udeung',
                'kata_kunci' => ['nama', 'Udeung', 'makna', 'arti'],
                'jawaban_atau_konten' => 'Nama "Udeung" berasal dari kata dalam bahasa Aceh yang berarti "batu besar". Nama ini diambil karena di bagian timur desa terdapat formasi batu besar yang menjadi penanda sejarah. Batu ini masih ada hingga saat ini dan menjadi salah satu landmark desa.',
            ],
            [
                'kunci' => 'faq-um-005',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Siapa Kepala Desa Desa Udeung',
                'kata_kunci' => ['kepala desa', 'kepala desa', 'pemimpin', 'siapa'],
                'jawaban_atau_konten' => 'Kepala Desa Desa Udeung saat ini adalah Bapak yang menjabat berdasarkan hasil pemilihan umum desa. Untuk informasi terkini mengenai nama dan masa jabatan Kepala Desa, silakan hubungi Kantor Kepala Desa atau kunjungi kantor desa di hari kerja.',
            ],
            [
                'kunci' => 'faq-um-006',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Tugas dan Wewenang Kepala Desa',
                'kata_kunci' => ['kepala desa', 'tugas', 'wewenang', 'kewajiban'],
                'jawaban_atau_konten' => 'Kepala Desa adalah kepala desa yang bertugas: memimpin pemerintahan desa, mengelola keuangan desa, melayani administrasi penduduk, memfasilitasi kegiatan kemasyarakatan, dan melaporkan kepada camat. Kepala Desa dipilih oleh masyarakat untuk masa jabatan 6 tahun.',
            ],
            [
                'kunci' => 'faq-um-007',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kontak Kantor Kepala Desa Desa Udeung',
                'kata_kunci' => ['kontak', 'telepon', 'kantor kepala desa', 'hubungi'],
                'jawaban_atau_konten' => 'Kantor Kepala Desa Desa Udeung buka setiap hari kerja (Senin-Jumat) pukul 08.00-16.00 WIB. Alamat di Jalan Utama Desa Udeung, dekat Meunasah. Untuk informasi kontak terkini, silakan lihat papan informasi desa atau datang langsung ke kantor.',
            ],
            [
                'kunci' => 'faq-um-008',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cuaca di Desa Udeung',
                'kata_kunci' => ['cuaca', 'suhu', 'curah hujan', 'musim'],
                'jawaban_atau_konten' => 'Desa Udeung memiliki iklim tropis dengan suhu rata-rata 24-32 derajat Celcius. Musim hujan terjadi bulan November hingga Maret, musim kemarau April hingga Oktober. Curah hujan rata-rata 2.000-3.000 mm per tahun.',
            ],
            [
                'kunci' => 'faq-um-009',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Musim di Aceh Tengah',
                'kata_kunci' => ['musim', 'hujan', 'kemarau', 'pancaroba'],
                'jawaban_atau_konten' => 'Aceh Tengah mengalami dua musim utama: musim hujan (Oktober-Maret) dan musim kemarau (April-September). Pada musim hujan, waspadai potensi banjir dan longsor. Pada musim kemarau, suhu bisa mencapai 33 derajat Celcius siang hari.',
            ],
            [
                'kunci' => 'faq-um-010',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Lokasi dan Alamat Desa Udeung',
                'kata_kunci' => ['lokasi', 'alamat', 'koordinat', 'peta'],
                'jawaban_atau_konten' => 'Desa Udeung terletak di Kecamatan Bebesen, Kabupaten Aceh Tengah, Provinsi Aceh. Koordinat sekitar 4.5167 Lintang Utara, 96.6167 Bujur Timur. Akses dari Kota Takengon sekitar 15 km ke arah barat.',
            ],
            [
                'kunci' => 'faq-um-011',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jarak ke Kota Takengon',
                'kata_kunci' => ['jarak', 'Takengon', 'kota', 'kabupaten'],
                'jawaban_atau_konten' => 'Jarak Desa Udeung ke Kota Takengon (ibukota Kabupaten Aceh Tengah) sekitar 15 kilometer. Ditempuh dalam waktu sekitar 30-45 menit menggunakan kendaraan bermotor atau mobil melalui jalan kabupaten.',
            ],
            [
                'kunci' => 'faq-um-012',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Akses Jalan ke Desa Udeung',
                'kata_kunci' => ['akses jalan', 'jalan', 'kendaraan', 'mobil'],
                'jawaban_atau_konten' => 'Akses jalan ke Desa Udeung sudah berupa jalan aspal yang dapat dilalui mobil dan kendaraan roda dua. Jalan utama dari Takengon sudah dalam kondisi baik. Beberapa jalan dusun masih berupa jalan tanah yang berlumpur saat hujan.',
            ],
            [
                'kunci' => 'faq-um-013',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Transportasi Umum ke Desa Udeung',
                'kata_kunci' => ['transportasi', 'kendaraan umum', 'angkutan', 'bus'],
                'jawaban_atau_konten' => 'Transportasi umum ke Desa Udeung terbatas. Tersedia angkutan pedesaan dari Terminal Takengon yang beroperasi pagi dan sore hari. Selain itu, masyarakat bisa menggunakan ojek pangkalan di pasar terdekat atau memesan ojek online.',
            ],
            [
                'kunci' => 'faq-um-014',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Ketersediaan Sinyal Telepon',
                'kata_kunci' => ['sinyal', 'telepon', 'seluler', 'jaringan'],
                'jawaban_atau_konten' => 'Sinyal telepon seluler di Desa Udeung tersedia dari provider Telkomsel, Indosat, dan XL. Kualitas sinyal bervariasi: Telkomsel paling stabil, sedangkan provider lain kadang lemah di area tertentu. Internet 4G sudah tersedia di sebagian wilayah.',
            ],
            [
                'kunci' => 'faq-um-015',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Koneksi Internet di Desa Udeung',
                'kata_kunci' => ['internet', 'wifi', 'broadband', 'koneksi'],
                'jawaban_atau_konten' => 'Internet di Desa Udeung tersedia melalui jaringan seluler 4G. Beberapa warung dan meunasah menyediakan akses WiFi gratis. Kecepatan internet bervariasi tergantung provider dan lokasi. Untuk kebutuhan internet stabil, disarankan menggunakan Telkomsel.',
            ],
            [
                'kunci' => 'faq-um-016',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Ketersediaan Listrik di Desa Udeung',
                'kata_kunci' => ['listrik', 'PLN', 'padam', 'arus listrik'],
                'jawaban_atau_konten' => 'Listrik di Desa Udeung dilayani oleh PLN dengan daya rumah tangga rata-rata 1.300-2.200 watt. Jadwal padam listrik terkadang terjadi saat pemeliharaan jaringan. Informasi jadwal padam diumumkan melalui pengeras suara atau media sosial desa.',
            ],
            [
                'kunci' => 'faq-um-017',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jam Padam Listrik di Desa Udeung',
                'kata_kunci' => ['padam', 'listrik', 'jadwal', 'mati lampu'],
                'jawaban_atau_konten' => 'Jam padam listrik di Desa Udeung biasanya diumumkan oleh PLN 1-2 hari sebelumnya. Padam terjadwal biasanya dilakukan pagi hari pukul 08.00-12.00 WIB untuk pemeliharaan. Untuk keluhan gangguan listrik, hubungi PLN 123.',
            ],
            [
                'kunci' => 'faq-um-018',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Sumber Air Bersih di Desa Udeung',
                'kata_kunci' => ['air bersih', 'sumur', 'PDAM', 'sumber air'],
                'jawaban_atau_konten' => 'Sumber air bersih di Desa Udeung berasal dari sumur bor dan PDAM. Sebagian besar rumah tangga memiliki sumur bor sendiri. Air PDAM belum menjangkau seluruh dusun. Kualitas air dari sumur bor cukup baik untuk kebutuhan sehari-hari.',
            ],
            [
                'kunci' => 'faq-um-019',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Fasilitas MCK di Desa Udeung',
                'kata_kunci' => ['MCK', 'kamar mandi', 'toilet', 'sanitasi'],
                'jawaban_atau_konten' => 'Fasilitas MCK di Desa Udeung sebagian besar sudah memiliki kamar mandi pribadi di rumah. Untuk fasilitas umum, tersedia MCK di Meunasah dan beberapa titik strategis. Kualitas sanitasi desa cukup baik dengan program ODF (Open Defecation Free).',
            ],
            [
                'kunci' => 'faq-um-020',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Keunggulan Desa Udeung',
                'kata_kunci' => ['keunggulan', 'unggulan', 'potensi', 'daya tarik'],
                'jawaban_atau_konten' => 'Keunggulan Desa Udeung antara lain: masyarakat yang religius dan guyub, udara sejuk pegunungan, lahan pertanian subur, adat istiadat Aceh yang masih terjaga, dan keindahan alam di sekitar desa. Potensi pengembangan: agrowisata dan wisata budaya.',
            ],
            [
                'kunci' => 'faq-um-021',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Fasilitas Umum di Desa Udeung',
                'kata_kunci' => ['fasilitas', 'umum', 'gedung', 'prasarana'],
                'jawaban_atau_konten' => 'Fasilitas umum di Desa Udeung meliputi: Meunasah Utama, kantor kepala desa, posyandu, lapangan olahraga, TPS3R, dan jalan penghubung antar dusun. Beberapa fasilitas masih dalam tahap pemeliharaan dan pengembangan.',
            ],
            [
                'kunci' => 'faq-um-022',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Potensi Pertanian Desa Udeung',
                'kata_kunci' => ['pertanian', 'padi', 'sayur', 'kebun', 'potensi'],
                'jawaban_atau_konten' => 'Potensi pertanian Desa Udeung meliputi: padi sawah, palawija, sayuran dataran tinggi, dan buah-buahan. Lahan pertanian tersedia di area subak dan kebun. Petani dapat mengakses bimbingan teknis dari Dinas Pertanian Kabupaten.',
            ],
            [
                'kunci' => 'faq-um-023',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pasar di Sekitar Desa Udeung',
                'kata_kunci' => ['pasar', 'belanja', 'kebutuhan', 'jual beli'],
                'jawaban_atau_konten' => 'Pasar terdekat dari Desa Udeung adalah Pasar Bebesen yang berjarak sekitar 3 km. Pasar buka setiap hari dengan hari pasar besar setiap Minggu. Masyarakat juga bisa berbelanja di warung-warung yang tersebar di dalam desa.',
            ],
            [
                'kunci' => 'faq-um-024',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Lembaga Keuangan di Desa Udeung',
                'kata_kunci' => ['bank', 'koperasi', 'lembaga keuangan', 'simpan pinjam'],
                'jawaban_atau_konten' => 'Desa Udeung memiliki Baitul Mal Desa untuk pengelolaan zakat dan infaq. Untuk layanan perbankan, ATM terdekat berada di Pasar Bebesen. Koperasi simpan pinjam juga tersedia untuk kebutuhan pinjaman masyarakat.',
            ],
            [
                'kunci' => 'faq-um-025',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Layanan Kesehatan di Desa Udeung',
                'kata_kunci' => ['kesehatan', 'puskesmas', 'klinik', 'dokter'],
                'jawaban_atau_konten' => 'Desa Udeung belum memiliki fasilitas kesehatan sendiri. Puskesmas terdekat berada di Kecamatan Bebesen, berjarak sekitar 5 km. Untuk keadaan darurat, hubungi nomor 112 atau Kepala Desa untuk bantuan evakuasi ke fasilitas kesehatan.',
            ],
            [
                'kunci' => 'faq-um-026',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Fasilitas Pendidikan di Desa Udeung',
                'kata_kunci' => ['sekolah', 'pendidikan', 'SD', 'TPA'],
                'jawaban_atau_konten' => 'Desa Udeung memiliki satu sekolah dasar (SD Negeri) dan TPA di Meunasah. Untuk jenjang pendidikan lebih tinggi (SMP, SMA), masyarakat harus ke kecamatan atau kota Takengon. Pendidikan formal dan non-formal tersedia bagi seluruh warga.',
            ],
            [
                'kunci' => 'faq-um-027',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Keunggulan Alam Desa Udeung',
                'kata_kunci' => ['alam', 'pegunungan', 'udara sejuk', 'pemandangan'],
                'jawaban_atau_konten' => 'Desa Udeung memiliki keunggulan alam berupa udara sejuk khas dataran tinggi Aceh Tengah, pemandangan pegunungan, dan keaslian pedesaan. Potensi wisata alam meliputi: trekking, foto alam, dan menikmati sunrise dari bukit terdekat.',
            ],
            [
                'kunci' => 'faq-um-028',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Wisata di Sekitar Desa Udeung',
                'kata_kunci' => ['wisata', 'objek wisata', 'liburan', 'kunjungan'],
                'jawaban_atau_konten' => 'Objek wisata di sekitar Desa Udeung meliputi: Danau Laut Tawar (sekitar 20 km), Takengon sebagai kota wisata, dan beberapa air terjun di kecamatan tetangga. Desa ini juga bisa menjadi titik awal wisata pedesaan dan budaya Aceh Tengah.',
            ],
            [
                'kunci' => 'faq-um-029',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pengaduan dan Saran untuk Desa Udeung',
                'kata_kunci' => ['pengaduan', 'saran', 'keluhan', 'masukan'],
                'jawaban_atau_konten' => 'Saran dan pengaduan untuk Desa Udeung dapat disampaikan langsung ke Kantor Kepala Desa, melalui musyawarah desa, atau melalui media sosial resmi desa. Setiap saran akan ditindaklanjuti oleh perangkat desa dalam rapat evaluasi bulanan.',
            ],
            [
                'kunci' => 'faq-um-030',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kegiatan Musyawarah Desa',
                'kata_kunci' => ['musyawarah', 'rapat', 'musrenbang', 'keputusan'],
                'jawaban_atau_konten' => 'Musyawarah desa diadakan minimal 4 kali setahun untuk membahas program pembangunan. Musyawarah terbuka untuk seluruh warga. Keputusan musyawarah menjadi dasar perencanaan pembangunan desa. Jadwal musyawarah diumumkan oleh Kepala Desa.',
            ],
        ];
    }
}
